### ISSUE TITLE
Support for Small Taskbar

### ISSUE THREAD

**Issue by orditeck** [Tom60chat/DeskBand-Media-Controls#1]
Hi, first of all, thanks for this awesome project, it's exactly what I was looking for!

I personally have the "Use small taskbar buttons" setting on:

![image](https://user-images.githubusercontent.com/2186535/127751900-a607fcda-dfea-40db-bccf-af87ec9478e0.png)

When this setting is enabled, DeskBand's style doesn't adjust. 

![image](https://user-images.githubusercontent.com/2186535/127751950-73f39a79-2967-4317-8a97-8f34708ebc94.png)

Sorry for the photo instead of a screenshot lol it's because when I actually take a screenshot, [DeskBand overrides the height for the whole taskbar](https://i.imgur.com/FzUrUw1.png) for some reason!

Would be amazing to see a fix for this :) For the moment I unfortunately can't use it because of the resizing behavior of my taskbar caused by DeskBand.

**Comment by Tom60chat** [comment]
Hello, thank you for your return.
Support for the small taskbar was not planned, the DeskBand has a constant height.
I have already scheduled an update to fix a problem with screens that have different DPI, I will fix this problem at the same time.

**Comment by Tom60chat** [comment]
Hello,
The new version with small taskbar support has been released.
You can find here: [1.3.0](https://github.com/Tom60chat/DeskBand-Media-Controls/releases/tag/1.3.0)
